apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: events-scheduler-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - scheduler.xilonen.ru
    secretName: scheduler-tls
  rules:
  - host: scheduler.xilonen.ru
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: events-scheduler
            port:
              number: 80